basePath: /api/v1
definitions:
  common.Response:
    properties:
      code:
        description: 业务状态码，200表示成功
        type: integer
      data:
        description: 数据，用 interface{} 表示可以是任意类型
      msg:
        description: 提示信息
        type: string
    type: object
  models.Todo:
    properties:
      id:
        description: 主键
        type: integer
      status:
        description: 完成状态：true完成, false未完成
        type: boolean
      title:
        description: 任务标题
        type: string
      user_id:
        description: "\U0001F525 新增：外键关联"
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: 这是一个基于 Gin + GORM 的任务管理后端。
  title: Go Todo API
  version: "1.0"
paths:
  /todos:
    post:
      consumes:
      - application/json
      description: 需要传递 title 字段，user_id 会自动从 Token 获取
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 任务信息
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 创建一个新任务
      tags:
      - Todos
swagger: "2.0"
